config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get "users/check_email" =>"users#check_email"
  get "sessions/check_email" =>"sessions#check_email"
  get "preview" =>"announcements#preview"
  get "home" =>"announcements#home"

  get "previews" =>"generals#previews"

   get 'auth/:provider/callback', to: 'sessions#create'
   get 'auth/failure', to: redirect('/')
   get 'sign_out', to: 'sessions#destroy', as: 'sign_out'
   resources :users
   resources :generals
   resources :announcements
   resources :sessions do
    member do
      get 'confirmation'
    end
  end

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  has_many :visits
  has_many :latests
  belongs_to :user
  has_many :comments
	validates :title,
	:presence => true,
	:length => {:maximum => 30}

	validates :description, :presence => true

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :announcement
  belongs_to :general
  belongs_to :user
end

app/models/general.rb
class General < ActiveRecord::Base
  has_many :visits
  has_many :latests
  belongs_to :user
  has_many :comments
	validates :title,
	:presence => true,
	:length => {:maximum => 30}

	validates :description, :presence => true
end

app/models/latest.rb
class Latest < ActiveRecord::Base
  belongs_to :announcement
  belongs_to :general
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :latests
  has_many :announcements
  has_many :generals
  has_many :comments

 has_secure_password :validations => false

 validates :name, presence: true,
 :unless => proc{|u| u.provider.present?}

 validates :email,
 :presence => true,
 :uniqueness => {:case_sensitive => false},
 :format => {:with => ConfigCenter::GeneralValidations::EMAIL_FORMAT_REG_EXP},
 :unless => proc{|u| u.provider.present?}

 validates :password, :presence => true,
 :length => {:minimum => 6},
 :unless => proc{|u| u.provider.present?}, :if => '!password.nil?'

 mount_uploader :image, ImageUploader

 def self.authenticate(email, password)
  user = find_by_email(email)
  if user && user.password_digest == BCrypt::Engine.hash_secret(password, user.password_digest)
    user
  else
    nil
  end
end

def self.create_with_omniauth(auth)
 create! do |user|
  user.provider = auth['provider']
  user.uid = auth['uid']
  user.oauth_token = auth['oauth_token']
  if auth['info']
    user.name = auth['info']['name'] || ""
  end
end
end

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :announcement
   belongs_to :general
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
	skip_before_filter  :verify_authenticity_token
  before_filter :require_login


  def index
    @announcements = Announcement.all.order("updated_at desc")
    @visits = Visit.all
  end

  def create
    @announcement=Announcement.new(announcement_params)
    @announcement.user_id = current_user.id
    if @announcement.save
      @latest = Latest.new()
      @latest.announcement_id = @announcement.id
      @latest.user_id = current_user.id
      @latest.save
      redirect_to announcements_path
    else
     redirect_to '/'
   end
 end

 def new
  @announcement = Announcement.new
end

def preview
end

def show
  @announcements = Announcement.all.order("updated_at desc")
  @announcement=Announcement.find(params[:id])
  @visit = Visit.new()
  @visit.visitor_id = current_user.id
  @visit.announcement_id = @announcement.id
  @visit.save
  @visits = Visit.all.order("updated_at desc")
  respond_to do |format|
    format.js{}
  end
end

def home
  @latest = Latest.all.order("updated_at desc")
end

def edit
  @latest=Latest.find(params[:id])
  @comments = Comment.all.where(announcement_id: @latest.announcement_id)
end

def update
  @latest=Latest.find(params[:id])
  @comment = Comment.new(params.require(:comment).permit(:comment_text))
  if @comment.comment_text.present?
    @comment.announcement_id = @latest.announcement_id
    @comment.user_id = current_user.id
    @comment.save
    UserMailer.send_email(@latest,@comment).deliver
  end
  comments = Comment.all.where(announcement_id: params[:id].to_i)
  redirect_to edit_announcement_path(@latest)
end



def announcement_params
  params.require(:announcement).permit(:title,:description)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :set_cache_buster

  helper_method :current_user

  def current_user
  	@current_user ||= User.find_by_id(session[:user_id])
  end

  def require_login
  	unless session[:user_id]
  		flash[:error]="you must logged in to access this section!"
       redirect_to root_path # halts request cycle
     end
   end
   def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
  end
end

app/controllers/generals_controller.rb
class GeneralsController < ApplicationController
	skip_before_filter  :verify_authenticity_token
  before_filter :require_login

  def index
    @generals = General.all.order("updated_at desc")
    @visits = Visit.all
  end

  def create
    @general=General.new(general_params)
    @general.user_id = current_user.id
    if @general.save
      @latest = Latest.new()
      @latest.general_id = @general.id
       @latest.user_id = current_user.id
      @latest.save
      redirect_to generals_path
    else
     redirect_to '/'
   end
 end


 def show
  @generals = General.all.order("updated_at desc")
  @general=General.find(params[:id])
  @visit = Visit.new()
  @visit.visitor_id = current_user.id
  @visit.general_id = @general.id
  @visit.save
  respond_to do |format|
    format.js{}
  end
end

def new
  @general =General.new
end
def previews
end

def edit
  @latest=Latest.find(params[:id])
  @comments = Comment.all.where(general_id: @latest.general_id)
  end

  def update
    @latest=Latest.find(params[:id])
    @comment = Comment.new(params.require(:comment).permit(:comment_text))
    if @comment.comment_text.present?
    @comment.general_id = @latest.general_id
    @comment.user_id = current_user.id
    @comment.save
     UserMailer.send_email(@latest,@comment).deliver
  end
    comments = Comment.all.where(general_id: params[:id].to_i)
    redirect_to edit_general_path(@latest)
  end

def general_params
  params.require(:general).permit(:title,:description)
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def new
  respond_to do |format|
    format.js{}
  end
end
def check_email
  @user = User.find_by_email(params[:email])
  respond_to do |format|
    format.json { render :json => @user.present? }

  end
end

def create
  if params[:provider] == "google_oauth2"
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
  else
    user = User.authenticate(params[:email], params[:password])
  end
  if user && user.email_confirmation == true
    session[:user_id] = user.id
    flash[:success] = "Signed in Successfully"
    redirect_to home_path, :success => "Logged in!"
  else
    flash[:alert] = "Email ID not confirmed, Please check your email"
    redirect_to root_path
  end
end

def confirmation
    @user = User.find(params[:id])
    session[:user_id] = @user.id
    @user.update(email_confirmation: true)
    redirect_to home_path
    flash[:success] = "Thank you for your email confirmation"
  end

def destroy
  session[:user_id] = nil
  redirect_to root_path
  flash[:alert] = "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login

  def check_email
    @user = User.find_by_email(params[:user][:email])

    respond_to do |format|
      format.json { render :json => !@user  }
    end
  end

  def new
    @user = User.new
    respond_to do |format|
      format.js{}
    end
  end

  def create
    @user = User.new(user_params)
    user_name = user_params[:name].titleize
    @user.name = user_name
    if @user.valid? && @user.errors.blank?
      @user.save
      @success = true
      UserMailer.confirm_mail(@user).deliver
      redirect_to root_path
      flash[:success] = "Please check your email to complete registration!"
    else
      @success = false
      redirect_to root_path
      flash[:error] = "Failed to sign up!"
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/announcements/_announcement_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Create Announcement</h4>
    </div>
    <div class="modal-body">
      <%= form_for :announcement, :url => {:action => "create"},remote: true, method: :post, html:{:class =>"form-horizontal", :id=>"announcement" } do |f| %>
      <div class="form-group">
       <label for="inputTitle" class="col-sm-3 control-label">Title * :</label>
       <div class="col-sm-7">
         <%= f.text_field :title, :class=>"form-control",:placeholder=>"Title"%>
       </div>
       <div class="col-sm-2"></div>
     </div>
     <div class="form-group">
      <label for="inputBody" class="col-sm-3 control-label">Body * :</label>
      <div class="col-sm-7">

       <%= f.text_area :description,:class=>"form-control", :placeholder=>"Description"%>
     </div>
     <div class="col-sm-2"></div>
   </div>

   <div class="modal-footer">
     <div style="float: left;">
      <%= link_to 'Preview', preview_path, :class => "btn btn-default preview-buttton", :remote => :true %>
    </div>

    <%= f.submit "OK", :class=>"btn btn-primary ok-btn-padding" %>
    <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
  </div>
</div>
<% end %>
</div>
</div>
</div>
</div>

app/views/announcements/_preview.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Announcement</h4>
    </div>
    <div class="modal-body" style="background-color:#fff;">
      <div class ="preview_scroll">
        <p id="title_span"></p>
        <p id='description_span'></p>

      </div>
    </div>
    <div class="modal-footer">

      <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
    </div>
  </div>
</div>


<script type='text/javascript'>
  var title = $('#announcement_title').val();
  var description = $('#announcement_description').val();
  updatePreview(title, description);
</script>

app/views/announcements/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Announcement</h4>
    </div>
    <div class="modal-body" style="background-color:#fff;">
      <div class ="preview_scroll">
        <p id="title_span"></p>
        <%="Title:"%><%=@announcement.title%>
        <p id='description_span'></p>
        <%="Description:"%><%=@announcement.description%>
      </div>
    </div>
    <div class="modal-footer">

      <button type="button" class="btn btn-default ok-btn-padding reload" data-dismiss="modal">Cancel</button>
    </div>
  </div>
</div>

app/views/announcements/_update.html.erb
<div class="container" id="font_color">
  <div class="comment-area">
    <div class="row">
      <div class="col-sm-12 commenmt-area-height backgroun">
        <% @comments.each do |comment| %>
        <div class="row">
          <div class="col-sm-2">
            <div class="strong text-right">User :</div>
          </div>
          <div class="col-sm-10"><%= comment.user.name %></div>
        </div>
        <div class="row comments-margin">
          <div class="col-sm-2">
            <div class="strong text-right">Comments :</div>
          </div>
          <div class="col-sm-10"><%= comment.comment_text %>
          </div>
        </div>
        <hr>
        <% end %>
      </div>
      <%= form_for :comment, url: announcement_path(@latest), :method => :patch, :id => "comment_form" do |f| %>
      <div class="row">
        <div class="col-sm-2">

          <div class="strong text-right">Add comments :</div>
        </div>
        <div class="col-sm-10">
          <%= f.text_area :comment_text, :placeholder =>"Add comments here ...", :rows =>"3", :id => "Description3", :class => "form-control" %>
        </div>
      </div>

      <div class="comments-buttons">
        <%= f.submit "OK", :class => "btn btn-primary ok-btn-padding" %>
        <%= button_tag "Cancel",:class =>"btn btn-default ok-btn-padding",type: :reset %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/announcements/edit.html.erb
<div class="back_color">
<div class="container">
    <div class="row">
      <div class="col-sm-2">
        <div class="strong text-right">Title :</div>
      </div>
      <div class="col-sm-10"><%= @latest.announcement.title%></div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        <div class="strong text-right">Description :</div>
      </div>
      <div class="col-sm-10">
        <%= @latest.announcement.description %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        <div class="strong text-right">Created By :</div>
      </div>
      <div class="col-sm-10">
        <%= @latest.user.name %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        <div class="strong text-right">Created At :</div>
      </div>
      <div class="col-sm-10">
        <%= @latest.announcement.created_at.strftime("%I:%M %P %b %d") %>
      </div>
    </div>
  </div>
  <br>
   <%= render partial: 'update'  %>
</div>

app/views/announcements/home.html.erb
<div class="container cotainer-margin">
  <div class="row">
    <div class="col-sm-8">
      <div role="tabpanel" class="forum-section">
        <ul class="nav nav-tabs">
          <li role="presentation" class="active"><a href="#Forum" aria-controls="home" role="tab" data-toggle="tab">Forum</a></li>
        </ul>
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="Forum">
            <ul>

              <li><%= link_to "Announcements",announcements_path%>
                <li><%= link_to "General Discussions",generals_path%></li>
                <li><a href="#">Domain Specific </a> </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="latest-threads">
          <div class="head">LATEST THREADS</div>
          <div class="content-area">
            <% if @latest.present? %>
            <% @latest.each do |latest| %>
            <%if latest.announcement_id? %>
            <%= link_to edit_announcement_path(latest), :method => :get do%>
            <div class="threads">
              <div class="user"><%= latest.announcement.user.name.titleize %></div>
              <div class="post-body"><%= truncate(latest.announcement.description, :ommision => "... Read More", :length => 70) %></div>
              <div class="date-time"><%= latest.announcement.created_at.strftime("%I:%M %P %b %d") %> </div>
              <% end %>
            </div>
            <% else %>
            <%= link_to edit_general_path(latest), :method => :get do%>
            <div class="threads">
              <div class="user"><%= latest.general.user.name.titleize %></div>
              <div class="post-body"><%= truncate(latest.general.description, :ommision => "... Read More", :length => 70) %></div>
              <div class="date-time"><%= latest.general.created_at.strftime("%I:%M %P %b %d") %> </div>
            </div>
            <% end %>
            <% end %>
            <% end %>
            <% else %>
            <div class="threads">
              <div class="post-body">No Threads Found</div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/announcements/index.html.erb
<div class="container cotainer-margin">
  <div class="row">
    <li> <%= button_to "Create Post",new_announcement_path,:method=> :get, remote: true,:class=>"btn btn-warning btn-md pull-right", 'data-toggle' => 'modal', 'data-target'=>'#myModal'%></li>
  </div>
  <% if @announcements.present? %>
  <div class="forum-table table_outer">
    <table class="table table-striped" >
     <thead >
      <tr>
        <th class="topic">Topics</th>
        <th class="statistics">Statistics</th>
      </tr>
    </thead>
  </table>
</div>
<div class="forum-table scrollingTable table_outer" style="margin-top:-20px">
  <table id="myTable" class="table table-striped">
    <tbody >
      <% @announcements.each do |announcement| %>
      <tr>
        <td class="topic">
          <div class="topic-name"><%= link_to announcement.title, announcement_path(announcement), :remote => true %></div>

          <%= "Created by: " %><%=  announcement.user.name.titleize %><br>
          <%= "Created at: " %><%= announcement.created_at.strftime("%I:%M %P %b %d") %><br>
        </td>
        <td class="statistics">
          <% visits = @visits.where(announcement_id: announcement.id).pluck(:id) %>
          <%="Views: "%><%= visits.length %>
        </td>
        <td class="last-post">
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
<div class="forum-table table_outer">
    <table class="table table-striped" >
     <thead >
      <tr>
        <th class="topic">No Records Found</th>
      </tr>
    </thead>
  </table>
</div>
<% end %>
</div>

app/views/announcements/new.js.erb
$('#popup_modal').html("<%= escape_javascript(render(:partial=>'announcements/announcement_modal')) %>");
$('#popup_modal').modal('show');
AnnouncementValidator()

app/views/announcements/preview.js.erb
$('#stack2').html("<%= escape_javascript(render(:partial=>'preview', :locals => {announcement: @announcement})) %>");
$('#stack2').modal('show');

app/views/announcements/show.js.erb
$('#stack2').html("<%= escape_javascript(render(:partial=>'show', :locals => {announcement: @announcement})) %>");
$('#stack2').modal('show');
refresh()

app/views/generals/_general.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">General Discussion</h4>
    </div>
    <div class="modal-body">
      <%= form_for :general, :url => {:action => "create"},remote: true, method: :post, html:{:class =>"form-horizontal", :id=>"general" } do |f| %>
      <div class="form-group">
       <label for="inputTitle" class="col-sm-3 control-label">Title * :</label>
       <div class="col-sm-7">
         <%= f.text_field :title, :class=>"form-control",:placeholder=>"Title"%>
       </div>
       <div class="col-sm-2"></div>
     </div>
     <div class="form-group">
      <label for="inputBody" class="col-sm-3 control-label">Body * :</label>
      <div class="col-sm-7">

       <%= f.text_area :description,:class=>"form-control", :placeholder=>"Description"%>
     </div>
     <div class="col-sm-2"></div>
   </div>

   <div class="modal-footer">
     <div style="float: left;">
      <%= link_to 'Preview',previews_path,:class => "btn btn-default preview-buttton", :remote => :true %>

    </div>

    <%= f.submit "OK", :class=>"btn btn-primary ok-btn-padding" %>
    <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
  </div>
</div>
<% end %>
</div>
</div>
</div>
</div>

app/views/generals/_preview1.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">General</h4>
    </div>
      <div class="modal-body" style="background-color:#fff;">
      <div class ="preview_scroll">
            <p id="title_span"></p>
            <p id='description_span'></p>

            </div>
      </div>
    <div class="modal-footer">

      <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
    </div>
  </div>
</div>


<script type='text/javascript'>
var title = $('#general_title').val();
var description = $('#general_description').val();
  generalPreview(title, description);
</script>

app/views/generals/_previews.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">General</h4>
    </div>
    <div class="modal-body" style="background-color:#fff;">
      <div class ="preview_scroll">
        <p id="title_span"></p>
        <p id='description_span'></p>

      </div>
    </div>
    <div class="modal-footer">

      <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
    </div>
  </div>
</div>


<script type='text/javascript'>
  var title = $('#general_title').val();
  var description = $('#general_description').val();
  generalPreview(title, description);
</script>

app/views/generals/_update.html.erb
<div class="container">
  <div class="comment-area">
   <div class="row">
    <div class="col-sm-12 commenmt-area-height">
      <% @comments.each do |comment| %>
      <div class="row">
        <div class="col-sm-2">
          <div class="strong text-right">User :</div>
        </div>
        <div class="col-sm-10"><%= comment.user.name %></div>
      </div>
      <div class="row comments-margin">
        <div class="col-sm-2">
          <div class="strong text-right">Comments :</div>
        </div>
        <div class="col-sm-10"><%= comment.comment_text %>
        </div>
      </div>
      <% end %>
    </div>
    <%= form_for :comment, url: general_path(@latest), :method => :patch, :id => "comment_form" do |f| %>
    <div class="row">
      <div class="col-sm-2">

        <div class="strong text-right">Add comments :</div>
      </div>
      <div class="col-sm-10">
        <%= f.text_area :comment_text, :placeholder =>"Add comments here ...", :rows =>"3", :id => "Description3", :class => "form-control" %>
      </div>
    </div>

    <div class="comments-buttons">

      <%= f.submit "OK", :class => "btn btn-primary ok-btn-padding" %>
      <%= button_tag "Cancel",:class =>"btn btn-default ok-btn-padding",type: :reset %>

    </div>
    <% end %>
  </div>
</div>
</div>

app/views/generals/index.html.erb
<div class="container cotainer-margin">
  <div class="row">
    <li> <%= button_to "Create Post",new_general_path,:method=> :get, remote: true,:class=>"btn btn-warning btn-md pull-right", 'data-toggle' => 'modal', 'data-target'=>'#myModal'%></li>
  </div>
  <% if @generals.present? %>
  <div class="forum-table table_outer">
    <table class="table table-striped" >
     <thead >
      <tr>
        <th class="topic">Topics</th>
        <th class="statistics">Statistics</th>
        <th class="last-post">Last post</th>
      </tr>
    </thead>
  </table>
</div>
<div class="forum-table scrollingTable table_outer" style="margin-top:-20px">

 <table id="myTable" class="table table-striped">


  <tbody >
    <% @generals.each do |general| %>
    <tr>
      <td>
        <div class="topic-name"><%= link_to general.title, general_path(general), :remote => true %></div>
        <%= "Created by: " %><%= general.user.name.titleize %><br>
        <%= "Created at: " %><%= general.created_at.strftime("%I:%M %P %b %d") %><br>
      </td>
      <td>
        <% visits = @visits.where(general_id: general.id).pluck(:id) %>

        <%="Views: "%><%= visits.length %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
<% else %>
<div class="forum-table table_outer">
    <table class="table table-striped" >
     <thead >
      <tr>
        <th class="topic">No Records Found</th>
      </tr>
    </thead>
  </table>
</div>
<% end %>
</div>

app/views/generals/new.js.erb
$('#popup_modal').html("<%= escape_javascript(render(:partial=>'generals/general')) %>");
$('#popup_modal').modal('show');
GeneralValidator()

app/views/generals/previews.js.erb
$('#stack2').html("<%= escape_javascript(render(:partial=>'previews', :locals => {:general => @general})) %>");
$('#stack2').modal('show');

app/views/generals/show.js.erb
$('#stack2').html("<%= escape_javascript(render(:partial=>'generals/show',:locals => {:general => @general})) %>");
$('#stack2').modal('show');
refresh()

app/views/layouts/common/_footer.html.erb
<script src="assets/js/jquery.js"></script>
<script src="assets/js/bootstrap.js"></script>

app/views/layouts/common/_header.html.erb
<!--    Header-->
<nav class="navbar navbar-inverse ">
  <div class="container">
    <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Interactive-Forum", home_path, :class => "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
        <li>
        <%= image_tag  current_user.image,  :alt =>"Image", :class => "img-rounded profile-pic" %>
        </li>
        <li>
          <h3 class="sharmila"><%= current_user.name %></h3>
        </li>

        <li>
          <%= button_to "Sign out", session_path(:id => current_user.id),:method=> :delete, :class=>"btn btn-success signup-login-btn", 'data-toggle' => 'modal', 'data-target'=>'#myModal'%></li>
          <% else %>

          <li>
            <%= button_to "Sign up", new_user_path ,:method=> :get, remote: true, :class=>"btn btn-success signup-login-btn", 'data-toggle' => 'modal', 'data-target'=>'#myModal'%>
          </li>
          <li>

            <%= button_to "sign in", new_session_path ,:method=> :get, remote: true, :class=>"btn btn-success signup-login-btn", 'data-toggle' => 'modal', 'data-target'=>'#myModal'%>

          </li>

          <% end %>

        </ul>
      </div>
    </div>

  </nav>

app/views/layouts/common/_signin_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Log In</h4>
    </div>
    <%= form_tag sessions_path , :class =>"form-horizontal", :id =>"sign_in", :method=> :post, authenticity_token: true  do |f| %>

    <div class="modal-body">

      <form class="form-horizontal">
        <div class="form-group">
          <label for="inputEmail" class="col-sm-3 control-label">Email id</label>
          <div class="col-sm-7">
            <%= text_field_tag :email,nil, :class =>"form-control",:id =>"inputemail", :placeholder => "email" %>
          </div>
          <div class="col-sm-2"></div>
        </div>
        <div class="form-group">
          <label for="inputPassword" class="col-sm-3 control-label">Password</label>
          <div class="col-sm-7">
            <%= password_field_tag :password,nil, :class =>"form-control",:id =>"inputPassword",:placeholder => "Password" %>
          </div>
          <div class="col-sm-2"></div>
        </div>
      </div>
      <div class="modal-footer">
        <%= submit_tag "Submit", :class =>"btn btn-primary ok-btn-padding" %>
        <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
        <br>
      </br>
      <center> <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      </center>

    </div>
    <% end %>
  </div>
</div>
</div>